[project]
name = "dfp_external_storage"
authors = [
    { name = "DevelopmentForPeople", email = "developmentforpeople@gmail.com" }
]
description = "S3 compatible external storage for Frappe and ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "minio==7.2.15"
]

[build-system]
requires = ["flit_core>=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]
# dev dependencies go here

[project.urls]
Homepage = "https://github.com/developmentforpeople/dfp_external_storage"
Repository = "https://github.com/developmentforpeople/dfp_external_storage.git"
"Bug Reports" = "https://github.com/developmentforpeople/dfp_external_storage/issues"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"